mysite/flashcards/urls.py
from django.urls import path

from . import views

app_name = "flashcards"

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:question_id>/", views.flashcards, name="flashcards"),
]

mysite/members/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "members"

urlpatterns = [
        path("login_user/", views.login_user, name="login_user"),
        path("logout_user/", views.logout_user, name="logout_user"),
        path("register_user/", views.register_user, name="register_user"),
        path("new_user/", views.new_user, name="new_user"),
]

mysite/mysite/urls.py
from django.contrib import admin, auth
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("flashcards/", include("flashcards.urls")),
    path("members/", include("django.contrib.auth.urls")),
    path("members/", include("members.urls")),
]

mysite/flashcards/models.py
from django.db import models
from django.utils import choices, timezone
from django.conf import settings


LANGUAGE_CHOICE = {
        "EN": "English",
        "RU": "Russian",
        }
        

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    pub_date = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    language = models.CharField(max_length=3, choices=LANGUAGE_CHOICE, null=True, blank=True)
    deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.question_text


class Answer(models.Model):
    answer_text = models.CharField(max_length=500)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    votes = models.IntegerField(default=0)
    pub_date = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    language = models.CharField(max_length=3, choices=LANGUAGE_CHOICE, null=True, blank=True)
    deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.answer_text

mysite/members/models.py
from django.db import models

# Create your models here.

mysite/members/forms.py
from django.contrib.auth.forms import BaseUserCreationForm
from django.contrib.auth.models import User
from django import forms


class RegisterUserForm(BaseUserCreationForm):
    email = forms.EmailField()
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)

    class Meta:
        model = User
        fields = ("username", 
                  "first_name", 
                  "last_name", 
                  "email", 
                  "password1", 
                  "password2"
                  )

mysite/flashcards/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404


from . import models


def index(request):
    context = {
            "questions": [(q.id, q.question_text) for q in models.Question.objects.all()]
            }
    return render(request, "flashcards/index.html", context)


def flashcards(request, question_id: int):
    question = get_object_or_404(models.Question, pk=question_id)
    context = {
            "question": question.question_text,
            }
    return render(request, "flashcards/flashcard.html", context)

mysite/members/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.http import HttpRequest
from django.contrib.auth.forms import UserCreationForm

from .forms import RegisterUserForm


def login_user(request: HttpRequest):
    if request.method == "POST":
        print("hello")
        
        try:
            username = request.POST["username"]
            password = request.POST["password"]
            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect(to="flashcards:index")

            messages.success(request, "Ivalid login data")
            return render(request, "authenticate/login_user.html", {})

        except Exception as e:
            messages.success(request, f"{e}")
            return render(request, "authenticate/login_user.html", {})

    return render(request, "authenticate/login_user.html", {})


def logout_user(request: HttpRequest):
    logout(request)
    messages.info(request, "You were logged out!")
    return redirect(to="flashcards:index")


def register_user(request: HttpRequest):
    if request.method == "POST":
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            email = form.cleaned_data["email"]
            password = form.cleaned_data["password1"]
            user = authenticate(username=username, password=password)
            login(request, user)
        # password = request.POST["password"]
        # check_password = request.POST["check_password"]
        # if password != check_password:
        #     return redirect(to="members:register_user")

        # username = request.POST["username"]
        # email = request.POST["email"]
            messages.success(request, "User registered successfuly")
            return redirect(to="flashcards:index")

        messages.info(request, "The form was filled out incorrectly.")
        return render(request, "authenticate/register_user.html", {"form": form})

    form = RegisterUserForm()
    return render(request, "authenticate/register_user.html", {"form": form})


def new_user(request: HttpRequest):
    return render(request, "authenticate/new_user.html", {})

mysite/flashcards/templates/flashcards/flashcard.html
{% extends "base/layout.html" %}
{% block content %}

<h1>{{ question }}</h1>

{% endblock content %}

mysite/flashcards/templates/flashcards/index.html
{% extends "base/layout.html" %}
{% block content %}

{% if user.username %}
  <h1>Hello, {{ user.username }}!</h1>
{% else %}
  <h1>Hello, whoever!</h1>
{% endif %}

<table>
  <th>The table</th>
{% if questions %}
  {% for id, question in questions %}
  <tr><td><a href={% url 'flashcards:flashcards' id %}>{{ id }}) {{ question }}</a></td></tr>
  {% endfor %}
{% endif %}
</table>

{% endblock content %}

mysite/members/templates/authenticate/login.html
{% extends "./layout.html" %}
{% block content %}
<p>
  <div>Here will be a LOGIN form</div>
</p>

<form action="" method=POST>
  {% csrf_token %}

  <div>
    <label for="InputEmail">Email address</label><br>
    <input type="email" id="InputEmail"><br>
  </div>
  <div>
    <label for="InputPassowrd">Password</label><br>
    <input type="password" id="InputPassowrd"><br><br>
  </div>
  <div>
    <input type="submit" value="Submit">
  </div>

</form>

{% endblock content %}

mysite/members/templates/authenticate/login_user.html
{% extends "base/layout.html" %}

{% block content %}

<p>
  <div>
    <h2>Login page</h2>
  </div>
</p>

<form action="" method="post">
  {% csrf_token %}

  <div> 
    <label for="Username">Username</label><br>
    <input type="text" id="Username" name="username" placeholder="username" required><br>
  </div>
  <div>
    <label for="InputPassowrd">Password</label><br>
    <input type="password" id="InputPassword" name="password" placeholder="password" required><br><br>
  </div>
  <div>
    <input type="submit" value="Submit">
  </div>

</form>

{% endblock content %}

mysite/members/templates/authenticate/new_user.html
{% extends "base/layout.html" %}
{% block content %}

<div>
  <a href="{% url 'members:login_user'  %}"  type="button" class="btn btn-primary btn-lg">Login</a>
  <a href="{% url 'members:register_user'  %}"  type="button" class="btn btn-primary btn-lg">Register</a>
</div>

{% endblock content %}

mysite/members/templates/authenticate/register_user.html
{% extends "base/layout.html" %}

{% block content %}

<p>
  <div>
    <h2>Registration page</h2>
  </div>
</p>

{{ form.non_field_errors }}
<form action="" method="post">
  {% csrf_token %}

  {% for field in form %}
  <div class="form-group"> 
    {% if field.help_text %}
    <label for="{{ field.id_for_label }}" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-custom-class="custom-tooltip" data-bs-title="{{ field.help_text }}">{{ field.label }}*</label><br>
    {% else %}
    <label for="{{ field.id_for_label }}">{{ field.label }}</label><br>
    {% endif %}
    {{ field }}
  </div>
  {% endfor %}

  <div>
    <input type="submit" value="Submit">
  </div>

</form>

{% endblock content %}

mysite/templates/base/alert.html
<div class="container">
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>{{ message }}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endfor %}
  {% endif %}
</div>

mysite/templates/base/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewpoint" content="width=device-width, initial-scale=1.0">

    <title>::Interview prep::</title>


  <!--bootstrap link to css-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

  </head>

  <body>
    <!-- Navigation Bar -->
    {% include "base/navbar.html" %}

  <div class="container px-5 text-left shadow-lg p-3 mb-5 rounded">
    <main>
      <!-- Alerts -->
      {% include "base/alert.html" %}

      <!-- Main content block -->
      {% block content %}{% endblock content %}
    </main>
  </div>

    <!--bootstrap link to JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script>
      const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
      const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
    </script>
  </body>
</html>

mysite/templates/base/navbar.html
<div class="container">
<nav class="navbar bg-primary navbar-expand-lg bg-body-tertiary" data-bs-theme="dark" style="background-color: #d19d24;">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'flashcards:index' %}">Interview-prep</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'flashcards:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>

        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'members:logout_user' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'members:new_user' %}">Login/Register</a>
        </li>
        {% endif %}

      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
</div><br><br>